### ISSUE TITLE
obsoleted Field Error

### ISSUE THREAD

**Issue by SumitNandha** [JalmarazMartn/BCDataSuport#1]
Field Tax Area Display Name (9004) of table Customer (18) is obsoleted, reason: This field is not needed and it should not be used.

Page Edit - Data Support has to close.

**Comment by JalmarazMartn** [comment]
Sumit thank you very much for the bug report!! This error is raised because an obsolet field is selected or edited. I will fix this issue in next release in a few days!! Thank you again.

**Comment by JalmarazMartn** [comment]
Fixed: Tool does not allow to select any obsolete field, to show, filter or edit.

Thanks Sumit!!
